### ISSUE TITLE
OperationExecutor fires post and pre-events without checking for result.

### ISSUE THREAD

**Issue by jspuij** [jspuij/RESTier#15]
I cannot infer whether this was intentional, but OperationExecutor fires it's pre and post event invocations without awaiting the results. This could lead to executing the action operation before the pre-event finishes or even that the post-event finishes before the pre-event is done.

https://github.com/OData/RESTier/blob/a1a807f5497afdc64d9ad587c378de0cc5d42326/src/Microsoft.Restier.AspNet/Operation/OperationExecutor.cs#L216-L232

**Comment by robertmclaws** [comment]
Well, ExecuteOperationAsync is awaitable, so we should definitely try to fix this. However, please resist the urge to refactor the DI in the rest of this class... we will rewrite it for V2.

**Comment by jspuij** [comment]
Done.
