### ISSUE TITLE
Reintroduce PropertyBag or think of something else.

### ISSUE THREAD

**Issue by jspuij** [jspuij/RESTier#8]
Commit 3e1be238 removed property bags from ApiBase and InvocationContext. They were put into the DI container and in subsequent commits completely removed from Restier.

However this makes it completely impossible to attach state to InvocationContext and it's subclasses. If it's important to attach state to a QueryContext, SubmitContext, ModelContext, OperationContext, you cannot. We should not use the DI container for this.

**Comment by robertmclaws** [comment]
Based on the discussion we're going to hold off on this for NOW, but we should definitely fix it when we re-architect the pipeline for V2.
